# To enable this function, run `supabase functions deploy gemini-chat`
# and then add your GEMINI_API_KEY to your Supabase project's secrets.
# For example: `supabase secrets set GEMINI_API_KEY="your_gemini_api_key_here"`
name = "gemini-chat"
runtime = "deno"
entrypoint = "index.ts"
main = "https://deno.land/std@0.168.0/http/server.ts"