// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://nesiwmsujsulwncbmcnc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5lc2l3bXN1anN1bHduY2JtY25jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA0NjkwNzEsImV4cCI6MjA3NjA0NTA3MX0.eZX7bcIt9CXM3ZaXily0DDIcqNB-YBP_SwRigzFS7Bg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);